print("Bienvenido Gestor de Usuarios")
nombre=input("Ingrese su nombre: ")
edad=input("Ingrese su edad: ")
email=input("Ingrese su email: ")
h_bar= "-" * (len(nombre)+40)
relleno_edad= " " * (len(h_bar)-15-len(str(edad)))
relleno_mail= " " * (len(h_bar)-10-len(email))
cierre= " " * (len(h_bar))


print(f"\n\t+{h_bar}+")
print(f"\t+{' '*20}{nombre}{' '*20}+")
print(f"\t+{h_bar}+")
print(f"\t+{' '*4}Edad: {edad} años{relleno_edad}+")
print(f"\t+{' '*4}mail: {email}{relleno_mail}+")
print(f"\t+{cierre}+")
print(f"\t+{h_bar}+\n") 